# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cfe61a8594e6d116634925e2db195da1d59d8235aeca8e5d2ba3435c662fe822b2b41c0822d2f7d0ef4af8a264cc5d2a33ef844b55266cc12c9e41dad2f6c29

test:
  secret_key_base: 31fbf0c537c35e3cd84ce83e4cf434d6c2455d3f2fe008c0d491dde92cc16c1157d9e6b86489a388b27234d17e9071a112b43e12474356cc9f64e5532d4d445e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
